version: '3.8'

services:
  app:
    build: .
    image: fatecmeets_app
    container_name: fatecmeets_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: fatecmeets_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fatecmeets
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: